run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - unused
    - ineffassign
    - misspell
    - unconvert
    - prealloc
  disable:
    - funlen
    - wsl
    - lll
    - err113
    - errcheck
    - gocyclo
    - godot
    - gocritic
    - gosec
    - unparam
    - staticcheck
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  exclude-dirs:
    - bin
    - data
    - dist
  exclude-files:
    - ".*\\.pb\\.go$"
